package me.dio.banco.util;

public enum TipoOperacaoConta {
	CADASTRAR_CONTA_CORRENTE,
	CADASTRAR_CONTA_POUPANCA,
	SACAR_CONTA_CORRENTE,
	SACAR_CONTA_POUPANÇA,
	DEPOSITAR_CONTA_CORRENTE,
	DEPOSITAR_CONTA_POUPANCA,
	TRANSFERIR_CONTA_CORRENTE_PARA_POUPANCA,
	TRANSFERIR_CONTA_POUPANCA_PARA_CORRENTE,
	TRANSFERIR_CONTA_CORRENTE_PARA_CORRENTE,
	TRANSFERIR_CONTRA_POUPANCA_PARA_POUPANCA, 
	TRANSFERIR_CONTA_POUPANCA_PARA_POUPANCA,
	EXTRATO_CONTA_CORRENTE,
	EXTRATO_CONTA_POUPANCA;
	

}
